apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: cloud-gateway-ingress
  namespace: store
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$2
spec:
  ingressClassName: nginx
  rules:
    - host: localhost
      http:
        paths:
          - path: /inventory(/|$)(.*)
            pathType: Prefix
            backend:
              service:
                name: cloud-gateway-service
                port:
                  number: 9090
