apiVersion: v1
kind: Service
metadata:
  name: inventory-service
  namespace: store
spec:
  selector:
    app: inventory-service
  ports:
    - name: http
      port: 80
      targetPort: 2011
  type: ClusterIP
